sudo: required

services:
  - docker

language: go

install:
  - "go get -u -v github.com/kardianos/govendor"
  - "govendor sync"

script: "go test -v ./..."

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker build -t vrutkovs/polna . &&
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker push vrutkovs/polna;
    fi
